SG-VacyPer/Models/SolicitudVacaciones.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SG_VacyPer.Models
{
    public class SolicitudVacaciones
    {
        [Key]
        [Display(Name = "ID")]
        public int IdSolicitudVacaciones { get; set; } = 0;


        [Required(ErrorMessage = "*Requerido")]
        [Display(Name = "ID. Empleado ")]
        [ForeignKey("Empleados")]
        public int IdEmpleado { get; set; } = 0;
        // Claves externas - FK
        public Empleados? Empleados { get; set; }


        [Required(ErrorMessage ="*Requerido")]
        [StringLength(10)]
        [Display(Name ="Doc. de identidad empleado")]
        public string DocIdentidad { get; set; } = string.Empty;

                
        [Required(ErrorMessage = "*Requerido")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de comienzo")]
        public DateTime FechaComienzo { get; set; } = DateTime.Now;


        [Required(ErrorMessage = "*Requerido")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de finalización")]
        public DateTime FechaFinalizacion { get; set; } = DateTime.Now;


        [Required(ErrorMessage = "*Requerido")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de solicitud")]
        public DateTime FechaSolicitud { get; set; } = DateTime.Now;

        
        [Required(ErrorMessage = "*Requerido")]
        [StringLength(15)]
        [Display(Name = "Estado")]
        public string Estado { get; set; } = "Borrador";

        
        [StringLength(200)]
        [Display(Name = "Comentarios")]
        public string? Comentarios { get; set; } = string.Empty;

        
        [StringLength(200)]
        [Display(Name = "Motivo del rechazo")]
        public string? MotivoRechazo { get; set; } = string.Empty;

        [Display(Name = "ID Vacaciones")]
        [ForeignKey("Vacaciones")]
        public int? IdVacaciones { get; set; } = 0;
        // Claves externas - FK
        public Vacaciones? Vacaciones { get; set; }

    }

}

SG-VacyPer/Controllers/SolicitudVacacionesController.cs
using Microsoft.AspNetCore.Mvc;
using SG_VacyPer.AppData;
using SG_VacyPer.Models;

namespace SG_VacyPer.Controllers
{
    public class SolicitudVacacionesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SolicitudVacacionesController(ApplicationDbContext db)
        {
            _db = db;
        }

        // LIST - LISTA DE LOS REGISTROS GRABADOS
        public IActionResult IndexSolicitudVacaciones()
        {
            IEnumerable<SolicitudVacaciones> objSolVacList = _db.SolicitudVacaciones;
            return View(objSolVacList);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR EL REGISTRO  
        public IActionResult CreateSolicitudVacaciones()
        {
            // valores iniciales
            Models.SolicitudVacaciones MyMmodel = new Models.SolicitudVacaciones();

            return View(MyMmodel);
        }


        // POST - GRABAR UN REGISTRO NUEVO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSolicitudVacaciones(SolicitudVacaciones obj)
        {
            // 
            var id_SolicitudVacaciones = obj.IdSolicitudVacaciones;
            
            if (ModelState.IsValid)
            {
                _db.SolicitudVacaciones.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Solicitud de Vacaciones creado exitosamente";
                return RedirectToAction("IndexSolicitudVacaciones");
            }
            return View(obj);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR ** EDITAR ** REGISTRO  
        public IActionResult EditSolicitudVacaciones(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var SolicitudVacacionesFromDb = _db.SolicitudVacaciones.Find(id);
            
            if (SolicitudVacacionesFromDb == null)
            {
                return NotFound();
            }

            return View(SolicitudVacacionesFromDb);
        }

        // POST - ACTUALIZAR REGISTRO EDITADO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSolicitudVacaciones(SolicitudVacaciones obj)
        {

            var id_SolicitudVacaciones = obj.IdSolicitudVacaciones;
            
            if (ModelState.IsValid)
            {
                _db.SolicitudVacaciones.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Solicitud de Vacaciones actualizado exitosamente";
                return RedirectToAction("IndexSolicitudVacaciones");
            }
            return View(obj);
        }

        // POST -------- ELIMINAR REGISTRO -------- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteSolicitudVacaciones(int? id)
        {
            var obj = _db.SolicitudVacaciones.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.SolicitudVacaciones.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Solicitud de Vacaciones borrado exitosamente";
            return RedirectToAction("IndexSolicitudVacaciones");

        }

    }
}

SG-VacyPer/Views/SolicitudVacaciones/CreateSolicitudVacaciones.cshtml
@{
    ViewData["Title"] = "CreateSolicitudVacaciones";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Solicitud de vacaciones</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <!-- ************** DATOS DEL FORMULARIO *********** -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Registrar datos</h3>
                </div>

               <!-- Se llama la vista parcial de EMPLEADOS -->
               <partial name="_DataSolicitudVacaciones" /> 

            </div>    <!-- /.card -->

        </div>  <!-- /.container-fluid -->
    </div>

    <!-- /.content -->
    @section Scripts
        {
        <!-- Vista parcial con validaciones y Scripts comunes para los formularios  -->
        <partial name="_FormsValidationScripts" />
    }

 </div>
 <!-- /.content-wrapper -->

SG-VacyPer/Views/SolicitudVacaciones/EditSolicitudVacaciones.cshtml
@{
    ViewData["Title"] = "EditSolicitudVacaciones";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Solicitud de vacaciones</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <!-- ************** DATOS DEL FORMULARIO *********** -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Registrar datos</h3>
                </div>

               <!-- Se llama la vista parcial de EMPLEADOS -->
               <partial name="_DataSolicitudVacaciones" /> 

            </div>    <!-- /.card -->

        </div>  <!-- /.container-fluid -->
    </div>

    <!-- /.content -->
    @section Scripts
        {
        <!-- Vista parcial con validaciones y Scripts comunes para los formularios  -->
        <partial name="_FormsValidationScripts" />
    }

 </div>
 <!-- /.content-wrapper -->

SG-VacyPer/Views/SolicitudVacaciones/IndexSolicitudVacaciones.cshtml
@model IEnumerable<SolicitudVacaciones>
@{
    ViewData["Title"] = "IndexSolicitudVacaciones";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Solicitud de vacaciones</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- ***************** CONTENIDO ***************** -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="col-6 text-end">
                <a asp-controller="SolicitudVacaciones" asp-action="CreateSolicitudVacaciones" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Nuevo registro
                </a>
            </div>
            <br />

            <!-- filtros -->
            <div class="row">
                <label class="control-label">&nbsp;&nbsp;&nbsp;&nbsp; Estado:</label>
                <div class="col-sm-1">
                    <!-- select -->
                    <div class="form-group">
                        <select id="IdFiltroEstado" >
                            <option>Todos</option>
                            <option>Borrador</option>
                            <option>Confirmada</option>
                            <option>Rechazada</option>
                        </select>
                    </div>
                </div>

                

                <div class="col-sm-2">
                    <!-- text input -->
                    <div class="form-group">
                        <label class="control-label">Fecha solicitud:</label>
                        <input id="IdFiltroFechaSolictud"  type="date" />
                    </div>
                </div>

                <div class="col-sm-2">
                    <!-- text input -->
                    <div class="form-group">
                        <label class="control-label">Fecha comienzo:</label>
                        <input id="IdFiltroFechaComisnzo"  type="date" />
                    </div>
                </div>

                <div class="col-sm-4">
                    <!-- text input -->
                    <div class="form-group">
                        <label class="control-label">Empleado:</label>
                        <input id="IdFiltroEmpleado"  />
                    </div>
                </div>

            </div>

            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Lista</h3>

                            <!-- SEARCH -->
                            <partial name="_IndexSearch" />

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0" style="height: 420px;">
                            <table class="table table-head-fixed text-nowrap">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Empleado</th>
                                        <th>Fecha de solictud</th>
                                        <th>Comienzo</th>
                                        <th>Finalización</th>
                                        <th>Estado</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>

                                <!-- ************ CARGA DE DATOS ***************** -->
                                <tbody>
                                    @foreach (var obj in Model)
                                    {

                                        <tr>
                                            <td width="5%">
                                                @obj.IdSolicitudVacaciones
                                            </td>
                                            <td width="20%">
                                                @obj.DocIdentidad
                                            </td>
                                            <td width="10%">
                                                @obj.FechaSolicitud.ToShortDateString()
                                            </td>
                                            <td width="10%">
                                                @obj.FechaComienzo.ToShortDateString()
                                            </td>
                                            <td width="10%">
                                                @obj.FechaFinalizacion.ToShortDateString()
                                            </td>
                                            <td width="10%">
                                                @obj.Estado
                                            </td>


                                            @{
                                                // datos para la vista parcial de las acciones del INDEX -->
                                                ViewData["AspController"] = "SolicitudVacaciones";
                                                ViewData["AspAction1"] = "DeleteSolicitudVacaciones";
                                                ViewData["AspAction2"] = "EditSolicitudVacaciones";
                                                ViewData["AspRouteId"] = obj.IdSolicitudVacaciones;
                                            }

                                            <!-- Controles: botones de Editar y Borrar -->
                                            <partial name="_IndexActionsControls" />

                                        </tr>
                                    }
                                </tbody>

                            </table>
                        </div>
                        <!-- /.card-body -->
                        <!-- Controles: PAGINACIÓN -->
                        <partial name="_IndexPagination" />

                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

SG-VacyPer/Views/SolicitudVacaciones/_DataSolicitudVacaciones.cshtml
@model SolicitudVacaciones

<!-- Vista parcial de los datos de SolicitudVacaciones  -->
<!-- /.card-header -->
<div class="card-body">
    <!-- ************** DATOS DEL FORMULARIO *********** -->
    <form method="post">

        @{
            // ID OCULTO PARA QUE SEA TRANSMITIDO EN EL POST DE *** EDITAR *** YA QUE SINO LO PROCESA COMO NUEVO REGISTRO 
            if (String.Equals(ViewData["Title"], "EditSolicitudVacaciones")) 
            {
                <input asp-for="IdSolicitudVacaciones" hidden/>
            }
           
        }
        
        <div class="row">

             <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="IdEmpleado"></label>
                    <input asp-for="IdEmpleado" class="form-control" />
                    <span asp-validation-for="IdEmpleado" class="text-danger"></span>
                </div>
            </div>

             <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="DocIdentidad"></label>
                    <input asp-for="DocIdentidad" class="form-control" />
                    <span asp-validation-for="DocIdentidad" class="text-danger"></span>
                </div>
            </div>
            
        </div>
               
        <div class="row">
           
            <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="FechaComienzo"></label>
                    <input asp-for="FechaComienzo" class="form-control" />
                    <span asp-validation-for="FechaComienzo" class="text-danger"></span>
                </div>
            </div>

            <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="FechaFinalizacion"></label>
                    <input asp-for="FechaFinalizacion" class="form-control" />
                    <span asp-validation-for="FechaFinalizacion" class="text-danger"></span>
                </div>
            </div>

            <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="FechaSolicitud"></label>
                    <input asp-for="FechaSolicitud" class="form-control" disabled/>
                    <span asp-validation-for="FechaSolicitud" class="text-danger"></span>
                </div>
            </div>


        </div>


         <div class="row">

           <div class="col-sm-2">
                <!-- select -->
                <div class="form-group">
                    <label asp-for="Estado"></label>
                    <select asp-for="Estado" class="form-control">
                        <option>Borrador</option>
                        <option>Confirmada</option>
                        <option>Rechazada</option>
                    </select>
                </div>
            </div>


            <div class="col-sm-2">
                <!-- text input -->
                <div class="form-group">
                    <label asp-for="IdVacaciones"></label>
                    <input asp-for="IdVacaciones" class="form-control" />
                    <span asp-validation-for="IdVacaciones" class="text-danger"></span>
                </div>
            </div>

        </div>


        <div class="row">
            <div class="col-sm-6">
                <!-- textarea -->
                <div class="form-group">
                    <label asp-for="Comentarios"></label>
                    <textarea asp-for="Comentarios" class="form-control" rows="3"></textarea>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-6">
                <!-- textarea -->
                <div class="form-group">
                    <label asp-for="MotivoRechazo"></label>
                    <textarea asp-for="MotivoRechazo" class="form-control" rows="3"></textarea>
                </div>
            </div>
        </div>               

        <!-- GRABAR / REGRESAR -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>

            <a asp-controller="SolicitudVacaciones" asp-action="IndexSolicitudVacaciones" class="btn btn-secondary">
                Regresar
            </a>
        </div>


    </form>
</div>
<!-- /.card-body -->