SG-VacyPer/Controllers/CalendarioController.cs
using Microsoft.AspNetCore.Mvc;
using SG_VacyPer.AppData;
using SG_VacyPer.Models;

namespace SG_VacyPer.Controllers
{
    public class CalendarioController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CalendarioController(ApplicationDbContext db)
        {
            _db = db;
        }

        // LIST - LISTA DE LOS REGISTROS GRABADOS
        public IActionResult IndexCalendario()
        {
            IEnumerable<Calendario> objCalendarioList = _db.Calendario;
            return View(objCalendarioList);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR EL REGISTRO  
        public IActionResult CreateCalendario()
        {

            return View();
        }


        // POST - GRABAR UN REGISTRO NUEVO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCalendario(Calendario obj)
        {

            // 
            var id_Calendario = obj.IdCalendario;
            
            if (ModelState.IsValid)
            {
                _db.Calendario.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Tipo de Calendario creado exitosamente";
                return RedirectToAction("IndexCalendario");
            }
            return View(obj);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR ** EDITAR ** REGISTRO  
        public IActionResult EditCalendario(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CalendarioFromDb = _db.Calendario.Find(id);
            
            if (CalendarioFromDb == null)
            {
                return NotFound();
            }

            return View(CalendarioFromDb);
        }

        // POST - GRABAR REGISTRO EDITADO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCalendario(Calendario obj)
        {

            var id_Calendario = obj.IdCalendario;
            
            if (ModelState.IsValid)
            {
                _db.Calendario.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Calendario actualizado exitosamente";
                return RedirectToAction("IndexCalendario");
            }
            return View(obj);
        }

        // POST -------- ELIMINAR REGISTRO -------- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCalendario(int? id)
        {
            var obj = _db.Calendario.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Calendario.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Calendario borrado exitosamente";
            return RedirectToAction("IndexCalendario");

        }

    }
}

SG-VacyPer/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using SG_VacyPer.AppData;
using SG_VacyPer.Models;

namespace SG_VacyPer.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly ApplicationDbContext _db;
        
        public EmpleadosController(ApplicationDbContext db)
        {
            _db = db;
        }

        // LIST - LISTA DE LOS REGISTROS GRABADOS
        public IActionResult IndexEmpleados()
        {
            IEnumerable<Empleados> objEmpleadosList = _db.Empleados;
            return View(objEmpleadosList);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR EL REGISTRO  
        public IActionResult CreateEmpleado()
        {
            // valores iniciales
            Models.Empleados MyMmodel = new Models.Empleados();
            MyMmodel.ResponsableId = 0;

            return View(MyMmodel);
        }

        // POST - GRABAR UN REGISTRO NUEVO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateEmpleado(Empleados obj)
        {

            // ESTO DEBO CAMBIARLO PARA VALIDAR EL DOCUMENTO DE IDENTIDAD
            var id_empleado = obj.IdEmpleado;
            if (obj.DocIdentidad == obj.NombreCompleto)
            {
                ModelState.AddModelError("DocIdentidad", "El documento de identidad ya existe.");
            }

            if (ModelState.IsValid)
            {
                _db.Empleados.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Empleado creado exitosamente";
                return RedirectToAction("IndexEmpleados");
            }
            return View(obj);
        }


        // GET - SE LLAMA AL FORMULARIO PARA CREAR ** EDITAR ** REGISTRO  
        public IActionResult EditEmpleado(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var EmpleadosFromDb = _db.Empleados.Find(id);
            // var EmpleadosFromDbFirst = _db.Empleados.FirstOrDefault(u=>u.Id == id);
            // var EmpleadosFromDbSingle = _db.Empleados.SingleOrDefault(u => u.Id == id);
            
            if (EmpleadosFromDb == null)
            {
                return NotFound();
            }

            return View(EmpleadosFromDb);
        }

        // POST - GRABAR REGISTRO EDITADO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditEmpleado(Empleados obj)
        {

            // ESTO DEBO CAMBIARLO PARA VALIDAR EL DOCUMENTO DE IDENTIDAD
            var id_empleado = obj.IdEmpleado;
            if (obj.DocIdentidad == obj.NombreCompleto)
            {
                ModelState.AddModelError("DocIdentidad", "El documento de identidad ya existe.");
            }

            if (ModelState.IsValid)
            {
                _db.Empleados.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Empleado actualizado exitosamente";
                return RedirectToAction("IndexEmpleados");
            }
            return View(obj);
        }

        // POST -------- ELIMINAR REGISTRO -------- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEmpleado(int? id)
        {
            var obj = _db.Empleados.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Empleados.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Empleado borrado exitosamente";
            return RedirectToAction("IndexEmpleados");

        }

    }
}

SG-VacyPer/Controllers/PermisosController.cs
using Microsoft.AspNetCore.Mvc;
using SG_VacyPer.AppData;
using SG_VacyPer.Models;

namespace SG_VacyPer.Controllers
{
    public class PermisosController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PermisosController(ApplicationDbContext db)
        {
            _db = db;
        }

        // LIST - LISTA DE LOS REGISTROS GRABADOS
        public IActionResult IndexPermisos()
        {
            IEnumerable<Permisos> objPermisosList = _db.Permisos;
            return View(objPermisosList);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR EL REGISTRO  
        public IActionResult CreatePermiso()
        {

            return View();
        }


        // POST - GRABAR UN REGISTRO NUEVO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePermiso(Permisos obj)
        {

            // 
            var id_permisos = obj.IdPermisos;
            
            if (ModelState.IsValid)
            {
                _db.Permisos.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Tipo de permiso creado exitosamente";
                return RedirectToAction("IndexPermisos");
            }
            return View(obj);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR ** EDITAR ** REGISTRO  
        public IActionResult EditPermiso(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var PermisosFromDb = _db.Permisos.Find(id);
            
            if (PermisosFromDb == null)
            {
                return NotFound();
            }

            return View(PermisosFromDb);
        }

        // POST - GRABAR REGISTRO EDITADO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPermiso(Permisos obj)
        {

            var id_permisos = obj.IdPermisos;
            
            if (ModelState.IsValid)
            {
                _db.Permisos.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Tipo de permiso actualizado exitosamente";
                return RedirectToAction("IndexPermisos");
            }
            return View(obj);
        }

        // POST -------- ELIMINAR REGISTRO -------- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePermiso(int? id)
        {
            var obj = _db.Permisos.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Permisos.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Tipo de permiso borrado exitosamente";
            return RedirectToAction("IndexPermisos");

        }

    }
}

SG-VacyPer/Controllers/VacacionesController.cs
using Microsoft.AspNetCore.Mvc;
using SG_VacyPer.AppData;
using SG_VacyPer.Models;

namespace SG_VacyPer.Controllers
{
    public class VacacionesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VacacionesController(ApplicationDbContext db)
        {
            _db = db;
        }

        // LIST - LISTA DE LOS REGISTROS GRABADOS
        public IActionResult IndexVacaciones()
        {
            IEnumerable<Vacaciones> objVacacionesList = _db.Vacaciones;
            return View(objVacacionesList);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR EL REGISTRO  
        public IActionResult CreateVacaciones()
        {
            // valores iniciales
            Models.Vacaciones MyMmodel = new Models.Vacaciones();
            MyMmodel.DiasOficiales = 22;
            MyMmodel.DiasAdicionales = 0;

            return View(MyMmodel);
        }


        // POST - GRABAR UN REGISTRO NUEVO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateVacaciones(Vacaciones obj)
        {
            // 
            var id_Vacaciones = obj.IdVacaciones;
            
            if (ModelState.IsValid)
            {
                _db.Vacaciones.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Tipo de Vacaciones creado exitosamente";
                return RedirectToAction("IndexVacaciones");
            }
            return View(obj);
        }

        // GET - SE LLAMA AL FORMULARIO PARA CREAR ** EDITAR ** REGISTRO  
        public IActionResult EditVacaciones(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var VacacionesFromDb = _db.Vacaciones.Find(id);
            
            if (VacacionesFromDb == null)
            {
                return NotFound();
            }

            return View(VacacionesFromDb);
        }

        // POST - ACTUALIZAR REGISTRO EDITADO  ----- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditVacaciones(Vacaciones obj)
        {

            var id_Vacaciones = obj.IdVacaciones;
            
            if (ModelState.IsValid)
            {
                _db.Vacaciones.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Tipo de Vacaciones actualizado exitosamente";
                return RedirectToAction("IndexVacaciones");
            }
            return View(obj);
        }

        // POST -------- ELIMINAR REGISTRO -------- 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteVacaciones(int? id)
        {
            var obj = _db.Vacaciones.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Vacaciones.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Tipo de Vacaciones borrado exitosamente";
            return RedirectToAction("IndexVacaciones");

        }

    }
}

SG-VacyPer/Views/Shared/Z_OLD-Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SG_VacyPer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SG_VacyPer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SG_VacyPer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SG_VacyPer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SG-VacyPer/Views/Shared/_Footer.cshtml
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Trabajo de fin de estudio - Unir
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022. Todos los derechos reservados.
  </footer>

SG-VacyPer/Views/Shared/_FormsValidationScripts.cshtml
<!-- Vista parcial con validaciones y Scripts comunes para los formularios  -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function() {
        $("#datepicker1").datepicker({ dateFormat: 'dd/mm/yy' });
    });


    $(function() {
        $("#datepicker2").datepicker({ dateFormat: 'dd/mm/yy' });
    });

    $(function() {
        $("#datepicker3").datepicker({ dateFormat: 'dd/mm/yy' });
    });

    function confirmDelete(uniqueId, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();
        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>

<!-- Para que las validaciones se hangan del lado del cliente  -->
<partial name="_ValidationScriptsPartial" />

SG-VacyPer/Views/Shared/_IndexActionsControls.cshtml
<!-- INICIO: botones de Editar y Borrar -->
<td>
    <!-- <div class="card-footer">  -->
    <div class="w-30 btn-group" role="group">
        <form method="post" asp-controller="@ViewData["AspController"]" asp-action="@ViewData["AspAction1"]" asp-route-id="@ViewData["AspRouteId"]">
            <a asp-controller="@ViewData["AspController"]" asp-action="@ViewData["AspAction2"]"
               asp-route-id="@ViewData["AspRouteId"]" class="btn btn-primary">Editar</a>

            <span id="confirmDeleteSpan_@ViewData["AspRouteId"]" style="display:none">
                <span>¿Está seguro de borrar el registro?</span>
                <button type="submit" class="btn btn-danger">Sí</button>
                <a href="#" class="btn btn-primary"
                   onclick="confirmDelete('@ViewData["AspRouteId"]', false)">No</a>
            </span>

            <span id="deleteSpan_@ViewData["AspRouteId"]">
                <a href="#" class="btn btn-danger"
                   onclick="confirmDelete('@ViewData["AspRouteId"]', true)">Borrar</a>
            </span>
        </form>
    </div>
</td>
<!-- FIN: botones de Editar y Borrar -->

SG-VacyPer/Views/Shared/_IndexLogin.cshtml
<!--INICIO: LOGIN-->
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="../../index2.html" class="h1"><b>SG-VacyPer</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">Ingrese para comenzar su sesión</p>

            <form action="../../index3.html" method="post">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Recordarme
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" asp-controller="Home" asp-action="IndexLogin">Ingresar</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mt-2 mb-3" hidden>
                <a href="#" class="btn btn-block btn-primary">
                    <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                </a>
                <a href="#" class="btn btn-block btn-danger">
                    <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                </a>
            </div>
            <!-- /.social-auth-links -->

            <p class="mb-1" hidden>
                <a href="forgot-password.html">I forgot my password</a>
            </p>
            <p class="mb-0" hidden>
                <a href="register.html" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->
<!-- FIN: LOGIN -->

SG-VacyPer/Views/Shared/_IndexPagination.cshtml
<!-- INICIO: paginación -->
<div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
    </ul>
</div>
<!-- FIN: paginación -->

SG-VacyPer/Views/Shared/_IndexSearch.cshtml
<!-- INICIO: busqueda -->

<!--    NOTA: POR AHORA SIN ESTA FUNCIONALIDAD DE "SEARCH""
<div class="card-tools">
    <div class="input-group input-group-sm" style="width: 150px;">
        <input type="text" name="table_search" class="form-control float-right" placeholder="Buscar">

        <div class="input-group-append">
            <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </div>
</div>
-->
<!-- FIN: busqueda -->

SG-VacyPer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SG-VacyPer</title>

    <!-- SE CARGAN LOS ESTILOS DEL SITIO WEB (css) -->
    <partial name="_SiteStyles" />
        
    @await RenderSectionAsync("Styles", required: false)
   
</head>

<body>

    <partial name="_NavBar" />
    <partial name="_SideBar" />
    
    @RenderBody()

    <partial name="_Footer" />

    <!-- SE CARGAN LOS SCRIPTS DEL SITIO WEB (js) -->
    <partial name="_SiteScripts" />
    
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

SG-VacyPer/Views/Shared/_NavBar.cshtml
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="Index.cshtml" class="nav-link">Inicio</a> --> 
        <a class="nav-link " asp-controller="Home" asp-action="Index">Inicio</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contacto</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Buscar" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Fullscreen buttom -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
     
    </ul>
  </nav>
  <!-- /.navbar -->

SG-VacyPer/Views/Shared/_SideBar.cshtml
 <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a class="brand-link" asp-controller="Home" asp-action="Index">
        <!--<img src="~/AdminLTE/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
        <!--<img src="~/img/globe.svg" alt="SG-VacyPer Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
        <img src="~/img/UnirLogo.png" alt="Unir Logo" class="brand-image" style="opacity: .8">
        <span class="brand-text font-weight-light">SG-VacyPer</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">

            <!-- IMAGEN EMPLEADO  -->
            <div class="image">
                <!-- <img src="~/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> -->
                <img src="~/img/person-circle.svg" class="img-circle elevation-2" alt="User Image">
            </div>

            <!-- NOMBRE DEL EMPLEADO -->
            <div class="info">
                <a href="#" class="d-block">César Serrano</a>
            </div>
        </div>


        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Buscar" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">

            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->

                <li class="nav-item menu-open">
                    <!-- tablas y configuraciones-->
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Registros
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vacaciones" asp-action="IndexVacaciones">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Vacaciones</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Permisos" asp-action="IndexPermisos">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Permisos</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendario" asp-action="IndexCalendario">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Calendario</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Empleados" asp-action="IndexEmpleados">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Empleados</p>
                            </a>
                        </li>


                    </ul>

                    <!-- Solcitudes-->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Solicitudes
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="SolicitudVacaciones" asp-action="IndexSolicitudVacaciones">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Solicitar vacaciones</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Solicitar permisos</p>
                            </a>
                        </li>
                                                                        

                        <!--
                        <li class="nav-item">
                            <a href="pages/forms/validation.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Aprobaciones</p>
                            </a>
                        </li>
                        -->

                    </ul>
                </li>

                <!-- Informes -->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Informes
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Historial de vacaciones</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Historial de permisos</p>
                            </a>
                        </li>

                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->

    </div>
    <!-- /.sidebar -->
</aside>